

<!DOCTYPE html>
<html>
<body>

<h1>JavaScript Variables</h1>

<p>You can declare many variables in one statement.</p>

<p id="demo"></p>
<p id="demo2"></p>

<script>
//var person = "John Doe",
//carName = "Volvo",
price = 200;
var person = "shh",carName="honada",price ="500";
document.getElementById("demo2").innerHTML = carName;


var pi = 3.14;
//var person = "John Doe";
var answer = 'Yes I am!';

document.getElementById("demo").innerHTML = pi;
//document.getElementById("demo").innerHTML = person;
//document.getElementById("demo").innerHTML = answer;
</script>

</body>
</html>